global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "velu-app"
    metrics_path: /metrics
    scheme: http
    basic_auth:
      username: admin
      password: admin
    static_configs:
      - targets: ["caddy:80"]
